name: mptcourse

on:
  push:
    branches: [ main ]

env:
  DJANGO_SETTINGS_MODULE: mptcourse.settings
  VENV_PATH: .venv

jobs:
  build:
    name: Сборка и установка зависимостей
    runs-on: ubuntu-latest
    steps:
      - name: Получение кода
        uses: actions/checkout@v4

      - name: Установка Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.3'

      - name: Создание виртуального окружения и установка зависимостей
        run: |
          python3 -m venv "$VENV_PATH"
          source "$VENV_PATH/bin/activate"
          pip install -r requirements.txt

  migrations:
    name: Проверка миграций Django
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Получение кода
        uses: actions/checkout@v4

      - name: Установка Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.3'

      - name: Проверка миграций
        run: |
          source "$VENV_PATH/bin/activate"
          python manage.py makemigrations --check --dry-run

  lint:
    name: Проверка кода flake8
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Получение кода
        uses: actions/checkout@v4

      - name: Установка Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.3'

      - name: Запуск flake8
        run: |
          source "$VENV_PATH/bin/activate"
          pip install flake8
          flake8 main mptcourse --config=.flake8 || true

  static:
    name: Сборка статических файлов Django
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Получение кода
        uses: actions/checkout@v4

      - name: Установка Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.3'

      - name: Сборка статических файлов
        run: |
          source "$VENV_PATH/bin/activate"
          python manage.py collectstatic --noinput
