name: mptcourse

on:
  push:
    branches: [ master ]

jobs:
  validate:
    name: Проверка Django проекта
    runs-on: ubuntu-latest
    steps:
      - name: Получение репозитория
        uses: actions/checkout@v4

      - name: Установка Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.3'
        
      - name: Создание venv и установка зависимостей
        run: |
          python3 -m venv .venv
          source .venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Проверка проекта Django
        run: |
          source .venv/bin/activate
          echo "Проверка настроек Django"
          python3 manage.py check
          echo "Настройки валидны"

      - name: Проверка миграций Django
        run: |
          source .venv/bin/activate
          echo "Проверка миграций Django"
          python3 manage.py makemigrations --check --dry-run
          echo "Миграции валидны"

  test: 
    name: Проверка статических файлов Django
    runs-on: ubuntu-latest
    needs: validate
    steps:
      - name: Получение репозитория
        uses: actions/checkout@v4

      - name: Установка Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.3'
      
      - name: Создание venv и установка зависимостей
        run: |
          python3 -m venv .venv
          source .venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt

      - name: Проверка статических файлов Django
        run: |
          source .venv/bin/activate
          echo "Проверка статических файлов Django"
          python3 manage.py collectstatic --noinput --dry-run
          echo "Статические файлы валидны"
