name: mptcourse

on:
  push:
    branches: [ main ]

env:
  DJANGO_SETTINGS_MODULE: mptcourse.settings
  VENV_PATH: .venv

jobs:
  validate:
    name: Проверка Django проекта
    runs-on: ubuntu-latest
    steps:
      - name: Получение репозитория
        uses: actions/checkout@v4

      - name: Установка Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.3'
        
      - name: Создание venv и установка зависимостей
        run: |
          python3 -m venv "$VENV_PATH"
          source "$VENV_PATH/bin/activate"
          pip install -r requirements.txt

      - name: Проверка настроек Django
        run: |
          source "$VENV_PATH/bin/activate"
          python manage.py check

      - name: Проверка миграций Django
        run: |
          source "$VENV_PATH/bin/activate"
          python manage.py makemigrations --check --dry-run

      - name: Проверка flake8
        run: |
          source "$VENV_PATH/bin/activate"
          pip install flake8
          flake8 main mptcourse --config=.flake8 || true

  test: 
    name: Проверка статических файлов Django
    runs-on: ubuntu-latest
    needs: validate
    steps:
      - name: Получение репозитория
        uses: actions/checkout@v4

      - name: Установка Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.3'
      
      - name: Создание venv и установка зависимостей
        run: |
          python3 -m venv "$VENV_PATH"
          source "$VENV_PATH/bin/activate"
          pip install -r requirements.txt

      - name: Проверка статических файлов Django
        run: |
          source "$VENV_PATH/bin/activate"
          python manage.py collectstatic --noinput
